controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

main:
  path: /
  controller: App\Controller\Controller::main

tournament:
  path: /tournament/{id}
  controller: App\Controller\Controller::tournament

round:
  path: /results/{id}/{tournament}/{round}
  controller: App\Controller\Controller::results

tournaments:
  path: /tournaments/
  controller: App\Controller\Controller::tournaments
